name: Update run_status.json

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set running=true
        run: |
          echo '{"running": true}' > run_status.json
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add run_status.json
          git commit -m "Set running true"
          git push

      - name: Wait for 20 seconds
        run: sleep 20

      - name: Set running=false
        run: |
          echo '{"running": false}' > run_status.json
          git add run_status.json
          git commit -m "Set running false"
          git push
